[package]
name = "slog-term"
version = "1.3.3"
authors = ["Dawid Ciężarkiewicz <dpc@dpc.pw>"]
description = "Unix terminal drain and formatter for slog-rs"
keywords = ["slog", "logging", "log", "term"]
license = "MPL-2.0"
documentation = "https://docs.rs/slog-term"
homepage = "https://github.com/slog-rs/term"
repository = "https://github.com/slog-rs/term"
readme = "README.md"

[lib]
path = "lib.rs"

[dependencies]
slog = "1.2.1"
slog-stream = "1.2"
isatty = "0.1"
chrono = "0.2"
