[package]
name = "slog-term"
version = "2.0.0-alpha1"
authors = ["Dawid Ciężarkiewicz <dpc@dpc.pw>"]
description = "Unix terminal drain and formatter for slog-rs"
keywords = ["slog", "logging", "log", "term"]
license = "MPL-2.0"
documentation = "https://docs.rs/slog-term"
homepage = "https://github.com/slog-rs/slog"
repository = "https://github.com/slog-rs/term"
readme = "README.md"

[lib]
path = "lib.rs"

[dependencies]
slog = { git="http://github.com/slog-rs/slog", branch = "2.x.y" }
slog-stream = { git="http://github.com/slog-rs/stream", branch = "2.x.y"}
isatty = "0.1"
chrono = "0.2"
thread_local = "0.3"
